function data = get_integration_data(db, ship, survey, max_depth)

    sql = ['SELECT a.id, a.grid_id, a.line, a.start_lat, a.start_lon, a.end_lat, a.end_lon, '...
            'a.start_time, a.end_time, a.length, a.mean_speed, a.mean_ex_below_depth, '...
            'b.num_pings, c.class, sum(c.nasc) as nasc, d.station_id, d.shape '...
            'FROM interval a '...
            'JOIN interval_source b ON a.id = b.interval_id '...
            'JOIN integration_cell c ON a.id = c.interval_id and a.frequency_id = c.frequency_id '...
            'JOIN grid d ON a.grid_id = d.id '...
            'WHERE a.ship_id = ',num2str(ship),' AND a.survey_id = ',num2str(survey),' '...
            'AND c.max_depth <= ',num2str(max_depth),' '...
            'GROUP BY a.id, a.grid_id, a.line, a.start_lat, a.start_lon, a.end_lat, a.end_lon, '...
            'a.start_time, a.end_time, a.length, a.mean_speed, a.mean_ex_below_depth, b.num_pings, '...
            'c.class, d.station_id, d.shape'];
    data = dbQuery(db, sql, 'OutType', 'struct');
    
end
